CREATE TABLE problem (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
problem VARCHAR NOT NULL);

CREATE TABLE negativ (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
negativ VARCHAR NOT NULL,
problem_id INT NOT NULL,
CONSTRAINT FK_NEGATIV_PROBLEM FOREIGN KEY (problem_id) REFERENCES problem(id));

CREATE TABLE positiv (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
positiv VARCHAR NOT NULL,
negativ_id INT NOT NULL,
CONSTRAINT FK_POSITIV_NEGATIV FOREIGN KEY (negativ_id) REFERENCES negativ(id));